### ISSUE TITLE
error in freebsd 8.2

### ISSUE THREAD

**Issue by irulvam** [pixelb/ps_mem#18]
i have error like this
```javascript
 Private  +   Shared  =  RAM used       Program

Traceback (most recent call last):
  File "./ps_mem.py", line 494, in <module>
    sorted_cmds, shareds, count, total = get_memory_usage( pids_to_show, split_args )
  File "./ps_mem.py", line 396, in get_memory_usage
    cmd = getCmdName(pid, split_args)
  File "./ps_mem.py", line 261, in getCmdName
    cmdline = proc.open(pid, 'cmdline').read().split("\0")
IOError: [Errno 14] Bad address
```
i use freebsd 8.2.

**Comment by pixelb** [comment]
I think this is a bug in the linprocfs implementation for kernel processes.
I think this may be the fix? Please reopen if you think otherwise.
https://lists.freebsd.org/pipermail/freebsd-bugs/2011-June/044552.html
