### ISSUE TITLE
FreeBSD 11 Error

### ISSUE THREAD

**Issue by jwhulette** [pixelb/ps_mem#37]
I'm getting the following error:
Traceback (most recent call last):
  File "ps_mem.py", line 623, in <module>
    if __name__ == '__main__': main()
  File "ps_mem.py", line 576, in main
    verify_environment(pids_to_show)
  File "ps_mem.py", line 561, in verify_environment
    kernel_ver()
  File "ps_mem.py", line 217, in kernel_ver
    kv = proc.open('sys/kernel/osrelease').readline().split(".")[:3]
  File "ps_mem.py", line 126, in open
    raise LookupError
LookupError

root@sites:/usr/home/ec2-user # uname
FreeBSD

root@sites:/usr/home/ec2-user # freebsd-version
11.1-RELEASE-p8

**Comment by kiwicustom** [comment]
Same here:

$ sudo python ps_mem.py
Traceback (most recent call last):
  File "ps_mem.py", line 629, in <module>
    if __name__ == '__main__': main()
  File "ps_mem.py", line 582, in main
    verify_environment(pids_to_show)
  File "ps_mem.py", line 567, in verify_environment
    kernel_ver()
  File "ps_mem.py", line 221, in kernel_ver
    kv = proc.open('sys/kernel/osrelease').readline().split(".")[:3]
  File "ps_mem.py", line 126, in open
    raise LookupError
LookupError

---

$ freebsd-version
11.1-RELEASE-p9
