### ISSUE TITLE
unable to run script

### ISSUE THREAD

**Issue by rss9090** [pixelb/ps_mem#52]
I'm sorry but could you make an advise please how to run your script on FreeBSD? I try to run it via invoking from CLI from root command: "python ps_mem.py" and have this output:

Traceback (most recent call last):
  File "ps_mem.py", line 131, in open
    return open(self.path(*args), errors='ignore')
FileNotFoundError: [Errno 2] No such file or directory: '/compat/linux/proc/sys/kernel/osrelease'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ps_mem.py", line 660, in <module>
    if __name__ == '__main__': main()
  File "ps_mem.py", line 613, in main
    verify_environment(pids_to_show)
  File "ps_mem.py", line 594, in verify_environment
    kernel_ver()
  File "ps_mem.py", line 232, in kernel_ver
    kv = proc.open('sys/kernel/osrelease').readline().split(".")[:3]
  File "ps_mem.py", line 137, in open
    raise LookupError
LookupError

**Comment by pixelb** [comment]
It should have informed you that linprocfs is required, which I've now fixed
