### ISSUE TITLE
Windows 7 error

### ISSUE THREAD

**Issue by sergeevabc** [pixelb/ps_mem#67]
``` console
$ ver && python -V
Microsoft Windows [Version 6.1.7601]
Python 3.8.8

$ pip install ps_mem                               
Collecting ps_mem                                                                   
  Downloading ps_mem-3.12.tar.gz (18 kB)                                            
Using legacy 'setup.py install' for ps-mem, since package 'wheel' is not installed. 
Installing collected packages: ps-mem                                               
    Running setup.py install for ps-mem ... done                                    
Successfully installed ps-mem-3.12

$ ps_mem
Traceback (most recent call last):                                                 
  File "C:\Python\Scripts\ps_mem-script.py", line 33, in <module>                  
    sys.exit(load_entry_point('ps-mem==3.12', 'console_scripts', 'ps_mem')())      
  File "C:\Python\Scripts\ps_mem-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()                                                    
  File "c:\python\lib\importlib\metadata.py", line 77, in load                     
    module = import_module(match.group('module'))                                  
  File "c:\python\lib\importlib\__init__.py", line 127, in import_module           
    return _bootstrap._gcd_import(name[level:], package, level)                    
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                  
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked       
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module          
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed     
  File "c:\python\lib\site-packages\ps_mem.py", line 98, in <module>               
    PAGESIZE = os.sysconf("SC_PAGE_SIZE") / 1024 #KiB                              
AttributeError: module 'os' has no attribute 'sysconf'                             
```

**Comment by p3r7** [comment]
This tool is Linux/BSD only.

It may work under [WSL2](https://docs.microsoft.com/en-us/windows/wsl/about) but I'm not positive it will report usage of native Windows processes.

You might want to take a look at [tasklist](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tasklist) instead.
